<?php echo $this->doctype(); ?>
<html>
<head>
<meta charset="utf-8">
<?php echo $this->headTitle($this->translate('CContacts'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

</head>
    <body>
        <div class="container">
            
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
